import { AlgorithmMetadata } from "@/types/algorithms";

export const ALGORITHM_REGISTRY: AlgorithmMetadata[] = [
  // --- SEQUENTIAL ALGORITHMS ---
  {
    id: "bubble-sort",
    name: "Bubble Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "A simple comparison-based sorting algorithm that repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order.",
    timeComplexity: "O(N²)",
    spaceComplexity: "O(1)",
    workComplexity: "O(N²)",
    spanComplexity: "O(N²)",
    processorComplexity: "1",
    advantages: [
      "Simple to understand and implement",
      "Stable sorting (preserves original order of duplicates)",
      "In-place (requires no extra memory)",
    ],
    disadvantages: [
      "Extremely inefficient on large datasets",
      "Average and worst-case time complexity of O(N²)",
    ],
    applications: [
      "Education and academic demonstrations",
      "Detecting already-sorted or nearly-sorted arrays efficiently",
    ],
    pseudocode: [
      "procedure bubbleSort(A: list of sortable items)",
      "  n := length(A)",
      "  repeat",
      "    swapped := false",
      "    for i := 1 to n-1 inclusive do",
      "      if A[i-1] > A[i] then",
      "        swap(A[i-1], A[i])",
      "        swapped := true",
      "      end if",
      "    end for",
      "    n := n - 1",
      "  until not swapped",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 15,
  },
  {
    id: "selection-sort",
    name: "Selection Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "An in-place comparison sort that divides the array into sorted and unsorted sections, repeatedly finding the smallest element from the unsorted section and placing it at the end of the sorted section.",
    timeComplexity: "O(N²)",
    spaceComplexity: "O(1)",
    workComplexity: "O(N²)",
    spanComplexity: "O(N²)",
    processorComplexity: "1",
    advantages: [
      "In-place and simple",
      "Performs minimal memory writes (at most N swaps)",
    ],
    disadvantages: [
      "O(N²) complexity regardless of initial order",
      "Poor cache locality",
    ],
    applications: [
      "Useful when write cost is highly expensive",
      "Academic teaching of fundamental control loops",
    ],
    pseudocode: [
      "procedure selectionSort(A: list of items)",
      "  n := length(A)",
      "  for i := 0 to n-1 do",
      "    minIndex := i",
      "    for j := i+1 to n do",
      "      if A[j] < A[minIndex] then",
      "        minIndex := j",
      "      end if",
      "    end for",
      "    if minIndex != i then",
      "      swap(A[i], A[minIndex])",
      "    end if",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 15,
  },
  {
    id: "insertion-sort",
    name: "Insertion Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "Builds the final sorted array one item at a time by consuming one input element in each iteration and sliding it into its correct position.",
    timeComplexity: "O(N²)",
    spaceComplexity: "O(1)",
    workComplexity: "O(N²)",
    spanComplexity: "O(N²)",
    processorComplexity: "1",
    advantages: [
      "Efficient for small datasets",
      "Adaptive: O(N) if list is already sorted",
      "Online: can sort a list as it receives it",
    ],
    disadvantages: [
      "Inefficient for large arrays",
      "Expensive shifting operations",
    ],
    applications: [
      "Used as the base case for hybrid algorithms (e.g. Timsort)",
      "Sorting nearly sorted or real-time streaming data",
    ],
    pseudocode: [
      "procedure insertionSort(A: list)",
      "  for i := 1 to length(A)-1 do",
      "    key := A[i]",
      "    j := i - 1",
      "    while j >= 0 and A[j] > key do",
      "      A[j + 1] := A[j]",
      "      j := j - 1",
      "    end while",
      "    A[j + 1] := key",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 15,
  },
  {
    id: "merge-sort",
    name: "Merge Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "A divide-and-conquer algorithm that recursively splits the array into halves, sorts them, and merges the sorted halves back together.",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N log N)",
    spanComplexity: "O(N log N)",
    processorComplexity: "1",
    advantages: [
      "Guaranteed worst-case O(N log N) runtime",
      "Stable sort",
      "Highly effective for linked lists and external memory sorting",
    ],
    disadvantages: [
      "Requires auxiliary space of O(N)",
      "Slower in-practice than Quicksort for in-memory arrays",
    ],
    applications: [
      "External sorting (extremely large files)",
      "Custom library sorts requiring stability (e.g., Python, Java)",
    ],
    pseudocode: [
      "procedure mergeSort(A: list, l, r)",
      "  if l < r then",
      "    mid := floor((l + r) / 2)",
      "    mergeSort(A, l, mid)",
      "    mergeSort(A, mid + 1, r)",
      "    merge(A, l, mid, r)",
      "  end if",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
  },
  {
    id: "quick-sort",
    name: "Quick Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "A divide-and-conquer algorithm that partitions an array around a pivot element, placing smaller items before it and larger items after, then recursively sorting the sub-arrays.",
    timeComplexity: "O(N log N) avg",
    spaceComplexity: "O(log N) stack",
    workComplexity: "O(N log N)",
    spanComplexity: "O(N log N)",
    processorComplexity: "1",
    advantages: [
      "Fastest sorting algorithm in practice for cache locality",
      "Extremely small memory footprint",
    ],
    disadvantages: [
      "Worst-case O(N²) if pivot selections are poor",
      "Unstable sort",
    ],
    applications: [
      "Standard template library sorts in C/C++",
      "Embedded systems where space is at a premium",
    ],
    pseudocode: [
      "procedure quickSort(A, low, high)",
      "  if low < high then",
      "    p := partition(A, low, high)",
      "    quickSort(A, low, p - 1)",
      "    quickSort(A, p + 1, high)",
      "  end if",
      "end procedure",
      "procedure partition(A, low, high)",
      "  pivot := A[high]",
      "  i := low - 1",
      "  for j := low to high-1 do",
      "    if A[j] < pivot then",
      "      i := i + 1",
      "      swap(A[i], A[j])",
      "    end if",
      "  end for",
      "  swap(A[i + 1], A[high])",
      "  return i + 1",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
  },
  {
    id: "binary-search",
    name: "Binary Search",
    type: "sequential",
    category: "Searching",
    model: "RAM",
    description:
      "An efficient algorithm for finding an item from a sorted list of items by repeatedly halving the search interval.",
    timeComplexity: "O(log N)",
    spaceComplexity: "O(1)",
    workComplexity: "O(log N)",
    spanComplexity: "O(log N)",
    processorComplexity: "1",
    advantages: [
      "Logarithmic search time makes it extremely fast",
      "Constant space overhead",
    ],
    disadvantages: [
      "Requires the data to be strictly sorted beforehand",
      "Random access data structure (like an array) is necessary",
    ],
    applications: [
      "Database querying and primary key indexes",
      "Debugging via git bisect to find broken commits",
    ],
    pseudocode: [
      "procedure binarySearch(A, target)",
      "  low := 0, high := length(A) - 1",
      "  while low <= high do",
      "    mid := floor((low + high) / 2)",
      "    if A[mid] == target then",
      "      return mid",
      "    else if A[mid] < target then",
      "      low := mid + 1",
      "    else",
      "      high := mid - 1",
      "    end if",
      "  end while",
      "  return -1",
      "end procedure",
    ],
    defaultInputSize: 12,
    maxInputSize: 16,
  },
  {
    id: "bfs",
    name: "Breadth-First Search (BFS)",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "An algorithm for traversing or searching tree or graph data structures, exploring all nodes at the current depth before moving to nodes at the next depth level.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    workComplexity: "O(V + E)",
    spanComplexity: "O(V + E)",
    processorComplexity: "1",
    advantages: [
      "Guaranteed to find the shortest path in an unweighted graph",
      "Simple queue-based architecture",
    ],
    disadvantages: [
      "High memory overhead because it keeps all nodes of a level in the queue",
    ],
    applications: [
      "Shortest path routing protocols",
      "Social network connections (degrees of separation)",
      "Garbage collection (Cheney's copy algorithm)",
    ],
    pseudocode: [
      "procedure BFS(G, start_node)",
      "  let Q be a queue",
      "  label start_node as discovered",
      "  Q.enqueue(start_node)",
      "  while Q is not empty do",
      "    v := Q.dequeue()",
      "    for each neighbor w of v do",
      "      if w is not labeled as discovered then",
      "        label w as discovered",
      "        Q.enqueue(w)",
      "      end if",
      "    end for",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6, // 6 vertices
    maxInputSize: 10,
  },
  {
    id: "dfs",
    name: "Depth-First Search (DFS)",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "An algorithm for traversing or searching tree or graph data structures, exploring as deep as possible along each branch before backtracking.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    workComplexity: "O(V + E)",
    spanComplexity: "O(V + E)",
    processorComplexity: "1",
    advantages: [
      "Simple to understand and implement recursively",
      "Requires less memory than BFS for narrow, deep graph structures",
      "Well-suited for path finding and game state analysis",
    ],
    disadvantages: [
      "Not guaranteed to find the shortest path in unweighted graphs",
      "Can get trapped in infinite paths of infinite graphs",
    ],
    applications: [
      "Finding connected components and strongly connected components",
      "Topological sorting of Directed Acyclic Graphs (DAGs)",
      "Solving maze puzzles and game decision trees",
    ],
    pseudocode: [
      "procedure DFS(G, start_node)",
      "  let S be a stack",
      "  label start_node as discovered",
      "  S.push(start_node)",
      "  while S is not empty do",
      "    v := S.pop()",
      "    for each neighbor w of v do",
      "      if w is not labeled as discovered then",
      "        label w as discovered",
      "        S.push(w)",
      "      end if",
      "    end for",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 10,
  },
  {
    id: "astar",
    name: "A* Search Algorithm",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "An informed pathfinding and graph traversal algorithm that uses heuristics to find the shortest path between nodes more efficiently than Dijkstra's algorithm.",
    timeComplexity: "O(E log V)",
    spaceComplexity: "O(V)",
    workComplexity: "O(E log V)",
    spanComplexity: "O(E log V)",
    processorComplexity: "1",
    advantages: [
      "Highly optimal pathfinding when using admissible heuristics",
      "Extremely faster in practice compared to Dijkstra's algorithm",
      "Extensible: easy to adapt to grid maps, game worlds, and graphs",
    ],
    disadvantages: [
      "Heuristic functions must be carefully designed to be admissible (never overestimate)",
      "High memory usage as it must store all generated search nodes",
    ],
    applications: [
      "Video game pathfinding and character navigation",
      "Autonomous robotics map navigation and trajectory planning",
      "GPS navigation and digital maps routing",
    ],
    pseudocode: [
      "procedure AStar(G, source, goal, h)",
      "  for each vertex v in G:",
      "    gScore[v] := infinity, fScore[v] := infinity",
      "  gScore[source] := 0",
      "  fScore[source] := h(source)",
      "  openSet.push(source, fScore[source])",
      "  while openSet is not empty do",
      "    current := openSet.pop_min()",
      "    if current == goal then",
      "      return path",
      "    end if",
      "    for each neighbor of current:",
      "      alt := gScore[current] + weight(current, neighbor)",
      "      if alt < gScore[neighbor] then",
      "        parent[neighbor] := current",
      "        gScore[neighbor] := alt",
      "        fScore[neighbor] := gScore[neighbor] + h(neighbor)",
      "        openSet.push(neighbor, fScore[neighbor])",
      "      end if",
      "    end for",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 8,
  },
  {
    id: "dijkstra",
    name: "Dijkstra's Algorithm",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "Finds the single-source shortest paths between nodes in a graph with non-negative edge weights.",
    timeComplexity: "O((V + E) log V)",
    spaceComplexity: "O(V)",
    workComplexity: "O((V + E) log V)",
    spanComplexity: "O((V + E) log V)",
    processorComplexity: "1",
    advantages: [
      "Highly efficient for sparse graphs",
      "Guarantees shortest paths on positive weighted graphs",
    ],
    disadvantages: [
      "Does not support negative edge weights (loops infinitely or returns incorrect results)",
    ],
    applications: [
      "Network routing protocols (OSPF)",
      "Google Maps GPS navigation and route-finding systems",
    ],
    pseudocode: [
      "procedure Dijkstra(G, source)",
      "  for each vertex v in G:",
      "    dist[v] := infinity, visited[v] := false",
      "  dist[source] := 0",
      "  pq.push(source, 0)",
      "  while pq is not empty do",
      "    u := pq.pop_min()",
      "    if visited[u] continue",
      "    visited[u] := true",
      "    for each neighbor v of u:",
      "      alt := dist[u] + weight(u, v)",
      "      if alt < dist[v] then",
      "        dist[v] := alt",
      "        pq.push(v, alt)",
      "      end if",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 8,
  },

  // --- PARALLEL ALGORITHMS ---
  {
    id: "parallel-reduction",
    name: "Parallel Reduction (Sum)",
    type: "parallel",
    category: "Parallel Computing",
    model: "PRAM-EREW",
    description:
      "An algorithm that combines a collection of values using an associative binary operator (like addition or maximum) in parallel, constructing a binary tree of evaluations in O(log N) time steps.",
    timeComplexity: "O(log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N)",
    spanComplexity: "O(log N)",
    processorComplexity: "N / 2",
    advantages: [
      "Achieves exponential speedup from linear O(N) to O(log N) steps",
      "Uses optimal total work: O(N)",
    ],
    disadvantages: [
      "Requires synchronizing processors at every level of the reduction tree",
    ],
    applications: [
      "Computing sums, dot products, mins, or maxes of massive vectors in GPUs",
      "MapReduce frameworks where data needs aggregate stats",
    ],
    pseudocode: [
      "procedure ParallelReduction(A: array of size N)",
      "  for d := 1 to log2(N) do",
      "    for each processor P_i where i < N / (2^d) in parallel do",
      "      A[2 * i * 2^(d-1)] := A[2 * i * 2^(d-1)] + A[(2 * i + 1) * 2^(d-1)]",
      "    end parallel-for",
      "    synchronize / barrier()",
      "  end for",
      "  return A[0]",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
    defaultProcessorCount: 4,
    maxProcessorCount: 8,
  },
  {
    id: "parallel-prefix-sum",
    name: "Parallel Prefix Sum (Scan)",
    type: "parallel",
    category: "Parallel Computing",
    model: "PRAM-CREW",
    description:
      "Computes all prefix sums (cumulative running totals) of a sequence. Uses the Hillis-Steele algorithm to aggregate elements in O(log N) steps using N processors.",
    timeComplexity: "O(log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N log N)",
    spanComplexity: "O(log N)",
    processorComplexity: "N",
    advantages: [
      "Solves scan/prefix computation in highly optimized logarithmic steps",
      "Fundamental primitive for many other parallel algorithms",
    ],
    disadvantages: [
      "Non-work-optimal (performs O(N log N) additions instead of O(N))",
    ],
    applications: [
      "Parallel stream compaction and filtering",
      "Parallel Radix Sort partition calculation",
      "Evaluating polynomials in parallel",
    ],
    pseudocode: [
      "procedure ParallelPrefixSum(A: array of size N)",
      "  allocate temp[N]",
      "  for d := 1 to ceil(log2(N)) do",
      "    step := 2^(d-1)",
      "    for each processor P_i in parallel do",
      "      if i >= step then",
      "        temp[i] := A[i] + A[i - step]",
      "      else",
      "        temp[i] := A[i]",
      "      end if",
      "    end parallel-for",
      "    A := copy(temp) // barrier synchronization",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
    defaultProcessorCount: 8,
    maxProcessorCount: 16,
  },
  {
    id: "bitonic-sort",
    name: "Bitonic Sort",
    type: "parallel",
    category: "Sorting",
    model: "Hypercube",
    description:
      "A parallel comparison-based sorting network that constructs and sorts bitonic sequences (sequences that increase then decrease). Designed to run efficiently on Hypercubes or parallel GPUs.",
    timeComplexity: "O(log² N)",
    spaceComplexity: "O(N log² N)",
    workComplexity: "O(N log² N)",
    spanComplexity: "O(log² N)",
    processorComplexity: "N",
    advantages: [
      "Comparison structure is completely static and data-independent",
      "Extremely suitable for hardware custom implementation (FPGAs, GPUs)",
    ],
    disadvantages: [
      "Performs more comparisons than Quicksort: O(N log² N)",
      "Requires input sizes to be exactly powers of 2",
    ],
    applications: [
      "CUDA-based GPU sorting primitives",
      "Network routing switches for sorting packets",
    ],
    pseudocode: [
      "procedure BitonicSort(A: array of size N, power of 2)",
      "  for k := 2 to N, double each step do",
      "    for j := k/2 down to 1, half each step do",
      "      for each processor P_i where i < N in parallel do",
      "        ixj := i XOR j",
      "        if ixj > i then",
      "          ascending := ((i AND k) == 0)",
      "          if (ascending and A[i] > A[ixj]) or (not ascending and A[i] < A[ixj]) then",
      "            swap(A[i], A[ixj])",
      "          end if",
      "        end if",
      "      end parallel-for",
      "      barrier()",
      "    end for",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
    defaultProcessorCount: 8,
    maxProcessorCount: 16,
  },
  {
    id: "odd-even-sort",
    name: "Odd-Even Transposition Sort",
    type: "parallel",
    category: "Sorting",
    model: "Ring",
    description:
      "A parallel version of Bubble Sort running on a Ring or 1D array of processors. Alternates between odd-even and even-odd index comparisons, sorting the array in O(N) parallel steps.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N²)",
    spanComplexity: "O(N)",
    processorComplexity: "N / 2",
    advantages: [
      "Extremely simple interconnect (only adjacent processors talk)",
      "Zero routing overhead",
    ],
    disadvantages: [
      "Weak theoretical time complexity compared to O(log² N) sorts",
    ],
    applications: [
      "Systolic arrays and linear processor pipelines",
      "Teaching fundamental inter-processor communications",
    ],
    pseudocode: [
      "procedure OddEvenSort(A: array of size N)",
      "  for phase := 0 to N-1 do",
      "    if phase is even (even-odd phase) then",
      "      for each processor P_i (i even, i < N-1) in parallel do",
      "        if A[i] > A[i+1] then swap(A[i], A[i+1])",
      "      end parallel-for",
      "    else (odd-even phase) then",
      "      for each processor P_i (i odd, i < N-1) in parallel do",
      "        if A[i] > A[i+1] then swap(A[i], A[i+1])",
      "      end parallel-for",
      "    end if",
      "    barrier()",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 12,
    defaultProcessorCount: 4,
    maxProcessorCount: 6,
  },
  {
    id: "pointer-jumping",
    name: "Pointer Jumping (List Ranking)",
    type: "parallel",
    category: "Parallel Computing",
    model: "PRAM-EREW",
    description:
      "A parallel technique for finding the distance of every node in a linked list to the end of the list. By updating pointers to parent of parent, it shrinks path lengths logarithmically.",
    timeComplexity: "O(log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N log N)",
    spanComplexity: "O(log N)",
    processorComplexity: "N",
    advantages: [
      "Compresses long dependency paths from O(N) sequential to O(log N) parallel steps",
      "Applicable to trees (finding roots, depth, ancestor chains)",
    ],
    disadvantages: [
      "Needs random read access which can trigger memory conflicts",
    ],
    applications: [
      "Finding roots of forests in parallel graph components",
      "Evaluating parallel expression trees",
      "List ranking algorithms",
    ],
    pseudocode: [
      "procedure PointerJumping(next: array of pointers, d: array of distances)",
      "  for each processor P_i in parallel do",
      "    if next[i] == null then d[i] := 0 else d[i] := 1",
      "  end parallel-for",
      "  for step := 1 to ceil(log2(N)) do",
      "    for each processor P_i in parallel do",
      "      if next[i] != null then",
      "        d[i] := d[i] + d[next[i]]",
      "        next[i] := next[next[i]]",
      "      end if",
      "    end parallel-for",
      "    barrier()",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 12,
    defaultProcessorCount: 8,
    maxProcessorCount: 12,
  },
  {
    id: "parallel-bfs",
    name: "Parallel BFS",
    type: "parallel",
    category: "Graphs",
    model: "PRAM-CREW",
    description:
      "A parallelized version of graph exploration that processes all frontier nodes concurrently, writing newly visited nodes to the next frontier in parallel.",
    timeComplexity: "O(diameter * log V) avg",
    spaceComplexity: "O(V + E)",
    workComplexity: "O(V + E)",
    spanComplexity: "O(diameter * log V)",
    processorComplexity: "V",
    advantages: [
      "Massive speedup on graphs with small diameters (small-world networks)",
      "Utilizes concurrent reads to allow multiple frontier vertices to scan adjacent nodes",
    ],
    disadvantages: [
      "Undergoes write contention (requires CRCW or resolve conflicts) when adding to next frontier",
    ],
    applications: [
      "Social network analytics (analyzing connection components)",
      "Web crawlers scanning multiple pages in parallel",
    ],
    pseudocode: [
      "procedure ParallelBFS(G, start_node)",
      "  level[start_node] := 0",
      "  frontier := {start_node}",
      "  while frontier is not empty do",
      "    next_frontier := empty set",
      "    for each u in frontier in parallel do",
      "      for each neighbor v of u in parallel do",
      "        if level[v] is unassigned then",
      "          level[v] := level[u] + 1",
      "          add v to next_frontier (concurrent write/sync)",
      "        end if",
      "      end parallel-for",
      "    end parallel-for",
      "    frontier := next_frontier",
      "    barrier()",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 10,
    defaultProcessorCount: 4,
    maxProcessorCount: 8,
  },
];
