import { AlgorithmMetadata } from "@/types/algorithms";

export const ALGORITHM_REGISTRY: AlgorithmMetadata[] = [
  // --- SEQUENTIAL ALGORITHMS ---
  {
    id: "bubble-sort",
    name: "Bubble Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "A simple comparison-based sorting algorithm that repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order.",
    timeComplexity: "O(N²)",
    spaceComplexity: "O(1)",
    workComplexity: "O(N²)",
    spanComplexity: "O(N²)",
    processorComplexity: "1",
    advantages: [
      "Simple to understand and implement",
      "Stable sorting (preserves original order of duplicates)",
      "In-place (requires no extra memory)",
    ],
    disadvantages: [
      "Extremely inefficient on large datasets",
      "Average and worst-case time complexity of O(N²)",
    ],
    applications: [
      "Education and academic demonstrations",
      "Detecting already-sorted or nearly-sorted arrays efficiently",
    ],
    pseudocode: [
      "procedure bubbleSort(A: list of sortable items)",
      "  n := length(A)",
      "  repeat",
      "    swapped := false",
      "    for i := 1 to n-1 inclusive do",
      "      if A[i-1] > A[i] then",
      "        swap(A[i-1], A[i])",
      "        swapped := true",
      "      end if",
      "    end for",
      "    n := n - 1",
      "  until not swapped",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 15,
  },
  {
    id: "selection-sort",
    name: "Selection Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "An in-place comparison sort that divides the array into sorted and unsorted sections, repeatedly finding the smallest element from the unsorted section and placing it at the end of the sorted section.",
    timeComplexity: "O(N²)",
    spaceComplexity: "O(1)",
    workComplexity: "O(N²)",
    spanComplexity: "O(N²)",
    processorComplexity: "1",
    advantages: [
      "In-place and simple",
      "Performs minimal memory writes (at most N swaps)",
    ],
    disadvantages: [
      "O(N²) complexity regardless of initial order",
      "Poor cache locality",
    ],
    applications: [
      "Useful when write cost is highly expensive",
      "Academic teaching of fundamental control loops",
    ],
    pseudocode: [
      "procedure selectionSort(A: list of items)",
      "  n := length(A)",
      "  for i := 0 to n-1 do",
      "    minIndex := i",
      "    for j := i+1 to n do",
      "      if A[j] < A[minIndex] then",
      "        minIndex := j",
      "      end if",
      "    end for",
      "    if minIndex != i then",
      "      swap(A[i], A[minIndex])",
      "    end if",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 15,
  },
  {
    id: "insertion-sort",
    name: "Insertion Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "Builds the final sorted array one item at a time by consuming one input element in each iteration and sliding it into its correct position.",
    timeComplexity: "O(N²)",
    spaceComplexity: "O(1)",
    workComplexity: "O(N²)",
    spanComplexity: "O(N²)",
    processorComplexity: "1",
    advantages: [
      "Efficient for small datasets",
      "Adaptive: O(N) if list is already sorted",
      "Online: can sort a list as it receives it",
    ],
    disadvantages: [
      "Inefficient for large arrays",
      "Expensive shifting operations",
    ],
    applications: [
      "Used as the base case for hybrid algorithms (e.g. Timsort)",
      "Sorting nearly sorted or real-time streaming data",
    ],
    pseudocode: [
      "procedure insertionSort(A: list)",
      "  for i := 1 to length(A)-1 do",
      "    key := A[i]",
      "    j := i - 1",
      "    while j >= 0 and A[j] > key do",
      "      A[j + 1] := A[j]",
      "      j := j - 1",
      "    end while",
      "    A[j + 1] := key",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 15,
  },
  {
    id: "merge-sort",
    name: "Merge Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "A divide-and-conquer algorithm that recursively splits the array into halves, sorts them, and merges the sorted halves back together.",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N log N)",
    spanComplexity: "O(N log N)",
    processorComplexity: "1",
    advantages: [
      "Guaranteed worst-case O(N log N) runtime",
      "Stable sort",
      "Highly effective for linked lists and external memory sorting",
    ],
    disadvantages: [
      "Requires auxiliary space of O(N)",
      "Slower in-practice than Quicksort for in-memory arrays",
    ],
    applications: [
      "External sorting (extremely large files)",
      "Custom library sorts requiring stability (e.g., Python, Java)",
    ],
    pseudocode: [
      "procedure mergeSort(A: list, l, r)",
      "  if l < r then",
      "    mid := floor((l + r) / 2)",
      "    mergeSort(A, l, mid)",
      "    mergeSort(A, mid + 1, r)",
      "    merge(A, l, mid, r)",
      "  end if",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
  },
  {
    id: "quick-sort",
    name: "Quick Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "A divide-and-conquer algorithm that partitions an array around a pivot element, placing smaller items before it and larger items after, then recursively sorting the sub-arrays.",
    timeComplexity: "O(N log N) avg",
    spaceComplexity: "O(log N) stack",
    workComplexity: "O(N log N)",
    spanComplexity: "O(N log N)",
    processorComplexity: "1",
    advantages: [
      "Fastest sorting algorithm in practice for cache locality",
      "Extremely small memory footprint",
    ],
    disadvantages: [
      "Worst-case O(N²) if pivot selections are poor",
      "Unstable sort",
    ],
    applications: [
      "Standard template library sorts in C/C++",
      "Embedded systems where space is at a premium",
    ],
    pseudocode: [
      "procedure quickSort(A, low, high)",
      "  if low < high then",
      "    p := partition(A, low, high)",
      "    quickSort(A, low, p - 1)",
      "    quickSort(A, p + 1, high)",
      "  end if",
      "end procedure",
      "procedure partition(A, low, high)",
      "  pivot := A[high]",
      "  i := low - 1",
      "  for j := low to high-1 do",
      "    if A[j] < pivot then",
      "      i := i + 1",
      "      swap(A[i], A[j])",
      "    end if",
      "  end for",
      "  swap(A[i + 1], A[high])",
      "  return i + 1",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
  },
  {
    id: "heap-sort",
    name: "Heap Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "An in-place comparison sort that uses a binary heap data structure to find the maximum element, swap it to the end of the array, and restore the heap property.",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(1)",
    workComplexity: "O(N log N)",
    spanComplexity: "O(N log N)",
    processorComplexity: "1",
    advantages: [
      "In-place (requires O(1) auxiliary space)",
      "Guaranteed O(N log N) time complexity (no worst-case regression like Quick Sort)",
      "Great for systems where memory writes or extra allocations are limited",
    ],
    disadvantages: [
      "Not stable (reorders duplicate values)",
      "Poor cache locality compared to Quick Sort",
      "Slower in-practice than Quick Sort on modern CPUs",
    ],
    applications: [
      "Implementing priority queues",
      "Real-time embedded systems with strict memory bounds",
      "Order statistics (finding the k-th largest element)",
    ],
    pseudocode: [
      "procedure heapSort(A: list)",
      "  n := length(A)",
      "  for i := floor(n/2) - 1 down to 0 do",
      "    heapify(A, n, i)",
      "  end for",
      "  for i := n - 1 down to 1 do",
      "    swap(A[0], A[i])",
      "    heapify(A, i, 0)",
      "  end for",
      "end procedure",
      "procedure heapify(A, n, i)",
      "  largest := i",
      "  left := 2 * i + 1",
      "  right := 2 * i + 2",
      "  if left < n and A[left] > A[largest] then largest := left",
      "  if right < n and A[right] > A[largest] then largest := right",
      "  if largest != i then",
      "    swap(A[i], A[largest])",
      "    heapify(A, n, largest)",
      "  end if",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 15,
  },
  {
    id: "radix-sort",
    name: "Radix Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "A non-comparative sorting algorithm that sorts integers by grouping keys by individual digits that share the same significant position and value, typically starting from the least significant digit (LSD).",
    timeComplexity: "O(d · (N + k))",
    spaceComplexity: "O(N + k)",
    workComplexity: "O(d · (N + k))",
    spanComplexity: "O(d · (N + k))",
    processorComplexity: "1",
    advantages: [
      "Linear time complexity when keys can fit in fixed digits",
      "Stable sort",
      "Extremely efficient on large ranges of uniform values",
    ],
    disadvantages: [
      "Depends heavily on the size of digits/characters",
      "Not in-place (requires extra storage for buckets)",
      "Cannot easily handle floats or arbitrary structures without transformation",
    ],
    applications: [
      "Sorting zip codes, phone numbers, or dates",
      "Used on hardware architectures with parallel sorting capability",
      "High-performance database indexing routines",
    ],
    pseudocode: [
      "procedure radixSort(A: list)",
      "  maxVal := findMax(A)",
      "  exp := 1",
      "  while maxVal / exp > 0 do",
      "    countingSortByDigit(A, exp)",
      "    exp := exp * 10",
      "  end while",
      "end procedure",
      "procedure countingSortByDigit(A, exp)",
      "  n := length(A)",
      "  output := array of size n",
      "  count := array of size 10 initialized to 0",
      "  for i := 0 to n - 1 do",
      "    digit := floor(A[i] / exp) % 10",
      "    count[digit] := count[digit] + 1",
      "  end for",
      "  for i := 1 to 9 do",
      "    count[i] := count[i] + count[i - 1]",
      "  end for",
      "  for i := n - 1 down to 0 do",
      "    digit := floor(A[i] / exp) % 10",
      "    output[count[digit] - 1] := A[i]",
      "    count[digit] := count[digit] - 1",
      "  end for",
      "  copy output to A",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 15,
  },
  {
    id: "bucket-sort",
    name: "Bucket Sort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "A non-comparative partition-based sort that distributes array elements into a number of buckets, sorts each bucket individually (e.g. using Insertion Sort), and then concatenates the sorted buckets.",
    timeComplexity: "O(N + k) avg",
    spaceComplexity: "O(N + k)",
    workComplexity: "O(N + k)",
    spanComplexity: "O(N + k)",
    processorComplexity: "1",
    advantages: [
      "Linear time O(N) when inputs are uniformly distributed",
      "Highly parallelizable since each bucket can be sorted independently",
      "Stable sort",
    ],
    disadvantages: [
      "Worst-case O(N²) if many elements fall into a single bucket",
      "Extra space complexity for buckets",
      "Requires a good distribution function",
    ],
    applications: [
      "Sorting uniformly distributed floating-point numbers",
      "Sorting large databases spread across distributed nodes",
      "Pre-sorting phase in distributed computing environments",
    ],
    pseudocode: [
      "procedure bucketSort(A: list, bucketCount)",
      "  buckets := list of empty buckets",
      "  for i := 0 to length(A) - 1 do",
      "    idx := calculateBucketIndex(A[i])",
      "    insert A[i] into buckets[idx]",
      "  end for",
      "  for i := 0 to bucketCount - 1 do",
      "    sort(buckets[i])",
      "  end for",
      "  concatenate buckets into A",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 15,
  },
  {
    id: "binary-search",
    name: "Binary Search",
    type: "sequential",
    category: "Searching",
    model: "RAM",
    description:
      "An efficient algorithm for finding an item from a sorted list of items by repeatedly halving the search interval.",
    timeComplexity: "O(log N)",
    spaceComplexity: "O(1)",
    workComplexity: "O(log N)",
    spanComplexity: "O(log N)",
    processorComplexity: "1",
    advantages: [
      "Logarithmic search time makes it extremely fast",
      "Constant space overhead",
    ],
    disadvantages: [
      "Requires the data to be strictly sorted beforehand",
      "Random access data structure (like an array) is necessary",
    ],
    applications: [
      "Database querying and primary key indexes",
      "Debugging via git bisect to find broken commits",
    ],
    pseudocode: [
      "procedure binarySearch(A, target)",
      "  low := 0, high := length(A) - 1",
      "  while low <= high do",
      "    mid := floor((low + high) / 2)",
      "    if A[mid] == target then",
      "      return mid",
      "    else if A[mid] < target then",
      "      low := mid + 1",
      "    else",
      "      high := mid - 1",
      "    end if",
      "  end while",
      "  return -1",
      "end procedure",
    ],
    defaultInputSize: 12,
    maxInputSize: 16,
  },
  {
    id: "bfs",
    name: "Breadth-First Search (BFS)",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "An algorithm for traversing or searching tree or graph data structures, exploring all nodes at the current depth before moving to nodes at the next depth level.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    workComplexity: "O(V + E)",
    spanComplexity: "O(V + E)",
    processorComplexity: "1",
    advantages: [
      "Guaranteed to find the shortest path in an unweighted graph",
      "Simple queue-based architecture",
    ],
    disadvantages: [
      "High memory overhead because it keeps all nodes of a level in the queue",
    ],
    applications: [
      "Shortest path routing protocols",
      "Social network connections (degrees of separation)",
      "Garbage collection (Cheney's copy algorithm)",
    ],
    pseudocode: [
      "procedure BFS(G, start_node)",
      "  let Q be a queue",
      "  label start_node as discovered",
      "  Q.enqueue(start_node)",
      "  while Q is not empty do",
      "    v := Q.dequeue()",
      "    for each neighbor w of v do",
      "      if w is not labeled as discovered then",
      "        label w as discovered",
      "        Q.enqueue(w)",
      "      end if",
      "    end for",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6, // 6 vertices
    maxInputSize: 10,
  },
  {
    id: "dfs",
    name: "Depth-First Search (DFS)",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "An algorithm for traversing or searching tree or graph data structures, exploring as deep as possible along each branch before backtracking.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    workComplexity: "O(V + E)",
    spanComplexity: "O(V + E)",
    processorComplexity: "1",
    advantages: [
      "Simple to understand and implement recursively",
      "Requires less memory than BFS for narrow, deep graph structures",
      "Well-suited for path finding and game state analysis",
    ],
    disadvantages: [
      "Not guaranteed to find the shortest path in unweighted graphs",
      "Can get trapped in infinite paths of infinite graphs",
    ],
    applications: [
      "Finding connected components and strongly connected components",
      "Topological sorting of Directed Acyclic Graphs (DAGs)",
      "Solving maze puzzles and game decision trees",
    ],
    pseudocode: [
      "procedure DFS(G, start_node)",
      "  let S be a stack",
      "  label start_node as discovered",
      "  S.push(start_node)",
      "  while S is not empty do",
      "    v := S.pop()",
      "    for each neighbor w of v do",
      "      if w is not labeled as discovered then",
      "        label w as discovered",
      "        S.push(w)",
      "      end if",
      "    end for",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 10,
  },
  {
    id: "astar",
    name: "A* Search Algorithm",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "An informed pathfinding and graph traversal algorithm that uses heuristics to find the shortest path between nodes more efficiently than Dijkstra's algorithm.",
    timeComplexity: "O(E log V)",
    spaceComplexity: "O(V)",
    workComplexity: "O(E log V)",
    spanComplexity: "O(E log V)",
    processorComplexity: "1",
    advantages: [
      "Highly optimal pathfinding when using admissible heuristics",
      "Extremely faster in practice compared to Dijkstra's algorithm",
      "Extensible: easy to adapt to grid maps, game worlds, and graphs",
    ],
    disadvantages: [
      "Heuristic functions must be carefully designed to be admissible (never overestimate)",
      "High memory usage as it must store all generated search nodes",
    ],
    applications: [
      "Video game pathfinding and character navigation",
      "Autonomous robotics map navigation and trajectory planning",
      "GPS navigation and digital maps routing",
    ],
    pseudocode: [
      "procedure AStar(G, source, goal, h)",
      "  for each vertex v in G:",
      "    gScore[v] := infinity, fScore[v] := infinity",
      "  gScore[source] := 0",
      "  fScore[source] := h(source)",
      "  openSet.push(source, fScore[source])",
      "  while openSet is not empty do",
      "    current := openSet.pop_min()",
      "    if current == goal then",
      "      return path",
      "    end if",
      "    for each neighbor of current:",
      "      alt := gScore[current] + weight(current, neighbor)",
      "      if alt < gScore[neighbor] then",
      "        parent[neighbor] := current",
      "        gScore[neighbor] := alt",
      "        fScore[neighbor] := gScore[neighbor] + h(neighbor)",
      "        openSet.push(neighbor, fScore[neighbor])",
      "      end if",
      "    end for",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 8,
  },
  {
    id: "dijkstra",
    name: "Dijkstra's Algorithm",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "Finds the single-source shortest paths between nodes in a graph with non-negative edge weights.",
    timeComplexity: "O((V + E) log V)",
    spaceComplexity: "O(V)",
    workComplexity: "O((V + E) log V)",
    spanComplexity: "O((V + E) log V)",
    processorComplexity: "1",
    advantages: [
      "Highly efficient for sparse graphs",
      "Guarantees shortest paths on positive weighted graphs",
    ],
    disadvantages: [
      "Does not support negative edge weights (loops infinitely or returns incorrect results)",
    ],
    applications: [
      "Network routing protocols (OSPF)",
      "Google Maps GPS navigation and route-finding systems",
    ],
    pseudocode: [
      "procedure Dijkstra(G, source)",
      "  for each vertex v in G:",
      "    dist[v] := infinity, visited[v] := false",
      "  dist[source] := 0",
      "  pq.push(source, 0)",
      "  while pq is not empty do",
      "    u := pq.pop_min()",
      "    if visited[u] continue",
      "    visited[u] := true",
      "    for each neighbor v of u:",
      "      alt := dist[u] + weight(u, v)",
      "      if alt < dist[v] then",
      "        dist[v] := alt",
      "        pq.push(v, alt)",
      "      end if",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 8,
  },
  {
    id: "prim",
    name: "Prim's Algorithm (MST)",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "A greedy algorithm that finds a Minimum Spanning Tree (MST) for a weighted undirected graph by starting from a root vertex and repeatedly picking the minimum-weight edge connecting a tree vertex to a non-tree vertex.",
    timeComplexity: "O(E log V)",
    spaceComplexity: "O(V + E)",
    workComplexity: "O(E log V)",
    spanComplexity: "O(E log V)",
    processorComplexity: "1",
    advantages: [
      "Extremely efficient for dense graphs using Fibonacci heaps",
      "Grows a single connected component step-by-step",
      "Simple priority queue iteration",
    ],
    disadvantages: [
      "Requires connected graph",
      "Slower on sparse graphs than Kruskal's if using basic arrays",
    ],
    applications: [
      "Network infrastructure design (telecoms, power grids, water supply)",
      "Cluster analysis in machine learning",
      "Distance-based approximation algorithms",
    ],
    pseudocode: [
      "procedure Prim(G, start_node)",
      "  MST := empty set, visited[start_node] := true",
      "  PQ.push(all edges from start_node)",
      "  while PQ is not empty do",
      "    (u, v, weight) := PQ.pop_min()",
      "    if visited[v] then continue",
      "    visited[v] := true",
      "    add edge (u, v) to MST",
      "    for each edge (v, w) in G:",
      "      if not visited[w] then PQ.push(v, w, weight)",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 8,
  },
  {
    id: "kruskal",
    name: "Kruskal's Algorithm (MST)",
    type: "sequential",
    category: "Graphs",
    model: "RAM",
    description:
      "A greedy Minimum Spanning Tree algorithm that sorts all graph edges by weight and repeatedly adds the lightest edge that does not form a cycle, using a Disjoint Set Union (DSU) data structure.",
    timeComplexity: "O(E log E)",
    spaceComplexity: "O(V + E)",
    workComplexity: "O(E log E)",
    spanComplexity: "O(E log E)",
    processorComplexity: "1",
    advantages: [
      "Optimal for sparse graphs",
      "Simple edge sorting and fast O(α(V)) cycle check with Union-Find",
      "Can run on disconnected graphs to produce a Minimum Spanning Forest",
    ],
    disadvantages: [
      "Requires pre-sorting all edges upfront",
      "Does not maintain a single growing tree during intermediate steps",
    ],
    applications: [
      "Circuit layout and VLSI design",
      "Cable TV network routing",
      "Image segmentation and boundary detection",
    ],
    pseudocode: [
      "procedure Kruskal(G)",
      "  MST := empty set",
      "  sort all edges E by weight ascending",
      "  makeSet(v) for each vertex v in G",
      "  for each edge (u, v) with weight w in sorted E do",
      "    if find(u) != find(v) then",
      "      add edge (u, v) to MST",
      "      union(u, v)",
      "    end if",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 8,
  },
  {
    id: "timsort",
    name: "Timsort",
    type: "sequential",
    category: "Sorting",
    model: "RAM",
    description:
      "A hybrid stable sorting algorithm derived from Merge Sort and Insertion Sort, designed to perform exceptionally well on real-world data containing pre-existing ordered sequences (runs).",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N log N)",
    spanComplexity: "O(N log N)",
    processorComplexity: "1",
    advantages: [
      "Adaptive O(N) best-case time complexity on nearly sorted arrays",
      "Stable sort (preserves order of duplicates)",
      "Standard default sorting algorithm in Python, Java, and Android V8",
    ],
    disadvantages: [
      "Requires auxiliary memory O(N) for merge operations",
      "Slightly higher code complexity than basic Merge Sort",
    ],
    applications: [
      "Default sorting in Python (list.sort, sorted)",
      "Default sorting for non-primitive arrays in Java (Arrays.sort)",
      "High performance production standard library sorting",
    ],
    pseudocode: [
      "procedure TimSort(A: array, RUN_SIZE)",
      "  n := length(A)",
      "  for i := 0 to n-1 step RUN_SIZE do",
      "    insertionSort(A, i, min(i + RUN_SIZE - 1, n - 1))",
      "  end for",
      "  size := RUN_SIZE",
      "  while size < n do",
      "    for left := 0 to n-1 step 2 * size do",
      "      mid := left + size - 1",
      "      right := min(left + 2 * size - 1, n - 1)",
      "      if mid < right then merge(A, left, mid, right)",
      "    end for",
      "    size := size * 2",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
  },
  {
    id: "greedy",
    name: "Greedy Algorithm (Fractional Knapsack)",
    type: "sequential",
    category: "Greedy & Optimization",
    model: "RAM",
    description:
      "An optimization algorithm that makes locally optimal choices at each step to find a global optimum. Demonstrates the Fractional Knapsack problem where items are sorted by value-to-weight density ratio and greedily selected to maximize total value.",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N log N)",
    spanComplexity: "O(N log N)",
    processorComplexity: "1",
    advantages: [
      "Intuitive logic and fast O(N log N) sorting step",
      "Guarantees provably optimal global solution for Fractional Knapsack",
      "Extremely memory efficient",
    ],
    disadvantages: [
      "Greedy choices do not work for 0/1 Knapsack without dynamic programming",
      "Requires problem to possess optimal substructure and greedy-choice property",
    ],
    applications: [
      "Resource allocation and bandwidth throttling",
      "Financial portfolio asset allocation",
      "Data compression (Huffman coding trees)",
      "Job and activity scheduling",
    ],
    pseudocode: [
      "procedure FractionalKnapsack(Items, Capacity)",
      "  compute density v[i] / w[i] for each item",
      "  sort Items by density descending",
      "  totalValue := 0, currentWeight := 0",
      "  for each item in sorted Items do",
      "    if currentWeight + item.weight <= Capacity then",
      "      currentWeight += item.weight",
      "      totalValue += item.value",
      "      take 100% of item",
      "    else",
      "      remaining := Capacity - currentWeight",
      "      totalValue += item.value * (remaining / item.weight)",
      "      take fraction (remaining / item.weight) of item",
      "      break",
      "    end if",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 10,
  },

  // --- PARALLEL ALGORITHMS ---
  {
    id: "parallel-reduction",
    name: "Parallel Reduction (Sum)",
    type: "parallel",
    category: "Parallel Computing",
    model: "PRAM-EREW",
    description:
      "An algorithm that combines a collection of values using an associative binary operator (like addition or maximum) in parallel, constructing a binary tree of evaluations in O(log N) time steps.",
    timeComplexity: "O(log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N)",
    spanComplexity: "O(log N)",
    processorComplexity: "N / 2",
    advantages: [
      "Achieves exponential speedup from linear O(N) to O(log N) steps",
      "Uses optimal total work: O(N)",
    ],
    disadvantages: [
      "Requires synchronizing processors at every level of the reduction tree",
    ],
    applications: [
      "Computing sums, dot products, mins, or maxes of massive vectors in GPUs",
      "MapReduce frameworks where data needs aggregate stats",
    ],
    pseudocode: [
      "procedure ParallelReduction(A: array of size N)",
      "  for d := 1 to log2(N) do",
      "    for each processor P_i where i < N / (2^d) in parallel do",
      "      A[2 * i * 2^(d-1)] := A[2 * i * 2^(d-1)] + A[(2 * i + 1) * 2^(d-1)]",
      "    end parallel-for",
      "    synchronize / barrier()",
      "  end for",
      "  return A[0]",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
    defaultProcessorCount: 8,
    maxProcessorCount: 16,
  },
  {
    id: "parallel-prefix-sum",
    name: "Parallel Prefix Sum (Scan)",
    type: "parallel",
    category: "Parallel Computing",
    model: "PRAM-CREW",
    description:
      "Computes all prefix sums (cumulative running totals) of a sequence. Uses the Hillis-Steele algorithm to aggregate elements in O(log N) steps using N processors.",
    timeComplexity: "O(log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N log N)",
    spanComplexity: "O(log N)",
    processorComplexity: "N",
    advantages: [
      "Solves scan/prefix computation in highly optimized logarithmic steps",
      "Fundamental primitive for many other parallel algorithms",
    ],
    disadvantages: [
      "Non-work-optimal (performs O(N log N) additions instead of O(N))",
    ],
    applications: [
      "Parallel stream compaction and filtering",
      "Parallel Radix Sort partition calculation",
      "Evaluating polynomials in parallel",
    ],
    pseudocode: [
      "procedure ParallelPrefixSum(A: array of size N)",
      "  allocate temp[N]",
      "  for d := 1 to ceil(log2(N)) do",
      "    step := 2^(d-1)",
      "    for each processor P_i in parallel do",
      "      if i >= step then",
      "        temp[i] := A[i] + A[i - step]",
      "      else",
      "        temp[i] := A[i]",
      "      end if",
      "    end parallel-for",
      "    A := copy(temp) // barrier synchronization",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 16,
    defaultProcessorCount: 8,
    maxProcessorCount: 16,
  },
  {
    id: "bitonic-sort",
    name: "Bitonic Sort",
    type: "parallel",
    category: "Sorting",
    model: "Hypercube",
    description:
      "A parallel comparison-based sorting network that constructs and sorts bitonic sequences (sequences that increase then decrease). Designed to run efficiently on Hypercubes or parallel GPUs.",
    timeComplexity: "O(log² N)",
    spaceComplexity: "O(N log² N)",
    workComplexity: "O(N log² N)",
    spanComplexity: "O(log² N)",
    processorComplexity: "N",
    advantages: [
      "Comparison structure is completely static and data-independent",
      "Extremely suitable for hardware custom implementation (FPGAs, GPUs)",
    ],
    disadvantages: [
      "Performs more comparisons than Quicksort: O(N log² N)",
      "Requires input sizes to be exactly powers of 2",
    ],
    applications: [
      "CUDA-based GPU sorting primitives",
      "Network routing switches for sorting packets",
    ],
    pseudocode: [
      "procedure BitonicSort(A: array of size N, power of 2)",
      "  for k := 2 to N, double each step do",
      "    for j := k/2 down to 1, half each step do",
      "      for each processor P_i where i < N in parallel do",
      "        ixj := i XOR j",
      "        if ixj > i then",
      "          ascending := ((i AND k) == 0)",
      "          if (ascending and A[i] > A[ixj]) or (not ascending and A[i] < A[ixj]) then",
      "            swap(A[i], A[ixj])",
      "          end if",
      "        end if",
      "      end parallel-for",
      "      barrier()",
      "    end for",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 16,
    maxInputSize: 16,
    defaultProcessorCount: 8,
    maxProcessorCount: 16,
  },
  {
    id: "odd-even-sort",
    name: "Odd-Even Transposition Sort",
    type: "parallel",
    category: "Sorting",
    model: "Ring",
    description:
      "A parallel version of Bubble Sort running on a Ring or 1D array of processors. Alternates between odd-even and even-odd index comparisons, sorting the array in O(N) parallel steps.",
    timeComplexity: "O(N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N²)",
    spanComplexity: "O(N)",
    processorComplexity: "N / 2",
    advantages: [
      "Extremely simple interconnect (only adjacent processors talk)",
      "Zero routing overhead",
    ],
    disadvantages: [
      "Weak theoretical time complexity compared to O(log² N) sorts",
    ],
    applications: [
      "Systolic arrays and linear processor pipelines",
      "Teaching fundamental inter-processor communications",
    ],
    pseudocode: [
      "procedure OddEvenSort(A: array of size N)",
      "  for phase := 0 to N-1 do",
      "    if phase is even (even-odd phase) then",
      "      for each processor P_i (i even, i < N-1) in parallel do",
      "        if A[i] > A[i+1] then swap(A[i], A[i+1])",
      "      end parallel-for",
      "    else (odd-even phase) then",
      "      for each processor P_i (i odd, i < N-1) in parallel do",
      "        if A[i] > A[i+1] then swap(A[i], A[i+1])",
      "      end parallel-for",
      "    end if",
      "    barrier()",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 12,
    defaultProcessorCount: 4,
    maxProcessorCount: 6,
  },
  {
    id: "pointer-jumping",
    name: "Pointer Jumping (List Ranking)",
    type: "parallel",
    category: "Parallel Computing",
    model: "PRAM-EREW",
    description:
      "A parallel technique for finding the distance of every node in a linked list to the end of the list. By updating pointers to parent of parent, it shrinks path lengths logarithmically.",
    timeComplexity: "O(log N)",
    spaceComplexity: "O(N)",
    workComplexity: "O(N log N)",
    spanComplexity: "O(log N)",
    processorComplexity: "N",
    advantages: [
      "Compresses long dependency paths from O(N) sequential to O(log N) parallel steps",
      "Applicable to trees (finding roots, depth, ancestor chains)",
    ],
    disadvantages: [
      "Needs random read access which can trigger memory conflicts",
    ],
    applications: [
      "Finding roots of forests in parallel graph components",
      "Evaluating parallel expression trees",
      "List ranking algorithms",
    ],
    pseudocode: [
      "procedure PointerJumping(next: array of pointers, d: array of distances)",
      "  for each processor P_i in parallel do",
      "    if next[i] == null then d[i] := 0 else d[i] := 1",
      "  end parallel-for",
      "  for step := 1 to ceil(log2(N)) do",
      "    for each processor P_i in parallel do",
      "      if next[i] != null then",
      "        d[i] := d[i] + d[next[i]]",
      "        next[i] := next[next[i]]",
      "      end if",
      "    end parallel-for",
      "    barrier()",
      "  end for",
      "end procedure",
    ],
    defaultInputSize: 8,
    maxInputSize: 12,
    defaultProcessorCount: 8,
    maxProcessorCount: 12,
  },
  {
    id: "parallel-bfs",
    name: "Parallel BFS",
    type: "parallel",
    category: "Graphs",
    model: "PRAM-CREW",
    description:
      "A parallelized version of graph exploration that processes all frontier nodes concurrently, writing newly visited nodes to the next frontier in parallel.",
    timeComplexity: "O(diameter * log V) avg",
    spaceComplexity: "O(V + E)",
    workComplexity: "O(V + E)",
    spanComplexity: "O(diameter * log V)",
    processorComplexity: "V",
    advantages: [
      "Massive speedup on graphs with small diameters (small-world networks)",
      "Utilizes concurrent reads to allow multiple frontier vertices to scan adjacent nodes",
    ],
    disadvantages: [
      "Undergoes write contention (requires CRCW or resolve conflicts) when adding to next frontier",
    ],
    applications: [
      "Social network analytics (analyzing connection components)",
      "Web crawlers scanning multiple pages in parallel",
    ],
    pseudocode: [
      "procedure ParallelBFS(G, start_node)",
      "  level[start_node] := 0",
      "  frontier := {start_node}",
      "  while frontier is not empty do",
      "    next_frontier := empty set",
      "    for each u in frontier in parallel do",
      "      for each neighbor v of u in parallel do",
      "        if level[v] is unassigned then",
      "          level[v] := level[u] + 1",
      "          add v to next_frontier (concurrent write/sync)",
      "        end if",
      "      end parallel-for",
      "    end parallel-for",
      "    frontier := next_frontier",
      "    barrier()",
      "  end while",
      "end procedure",
    ],
    defaultInputSize: 6,
    maxInputSize: 10,
    defaultProcessorCount: 4,
    maxProcessorCount: 8,
  },
];
